/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook-16.glb -T 
Files: macbook-16.glb [639.28KB] > C:\Users\dell\WebstormProjects\apple_macbook_clone\public\models\macbook-16-transformed.glb [629.72KB] (1%)
Author: jackbaeten (https://sketchfab.com/jackbaeten)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-m3-16-inch-2024-8e34fc2b303144f78490007d91ff57c4
Title: macbook pro M3 16 inch 2024
*/

import {useGLTF, useTexture} from '@react-three/drei';
import * as THREE from 'three';
// Type for the GLTF result
type GLTFResult = {
    nodes: {
        [key: string]: THREE.Mesh;
    };
    materials: {
        [key: string]: THREE.Material;
    };
};

interface MacbookModel16Props {
    color?: string;
    scale?: number | [number, number, number];
    position?: [number, number, number];
    rotation?: [number, number, number];
    // Add other THREE.Object3D properties that you actually need
    // For example:
    // matrix?: THREE.Matrix4;
    // quaternion?: THREE.Quaternion;
    // etc.
}

function MacbookModel16({...props}: MacbookModel16Props) {
    const {nodes, materials} = useGLTF('/models/macbook-16-transformed.glb') as unknown as GLTFResult;
    const texture = useTexture('/screen.png');
    return (
        <group
            dispose={null}
            {...props}>
            {/* Main Body */}
            <mesh
                geometry={nodes.Object_10.geometry}
                material={materials.material_0}
                rotation={[Math.PI / 2, 0, 0]}
            />

            {/* Screen */}
            <mesh
                material={materials.screen}
                material-map={texture}
                geometry={nodes.Object_123.geometry}
                rotation={[Math.PI / 2, 0, 0]}
            >
                <meshBasicMaterial attach="material" map={texture} toneMapped={false}/>
            </mesh>

            {/* Keyboard and Trackpad */}
            <mesh
                geometry={nodes.Object_16.geometry}
                material={materials.zhGRTuGrQoJflBD}
                rotation={[Math.PI / 2, 0, 0]}
            />

            {/* Other parts */}
            <mesh geometry={nodes.Object_20.geometry} material={materials.PaletteMaterial002}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh geometry={nodes.Object_22.geometry} material={materials.lmWQsEjxpsebDlK}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh geometry={nodes.Object_30.geometry} material={materials.LtEafgAVRolQqRw}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh geometry={nodes.Object_32.geometry} material={materials.iyDJFXmHelnMTbD}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh geometry={nodes.Object_34.geometry} material={materials.eJObPwhgFzvfaoZ}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh geometry={nodes.Object_38.geometry} material={materials.nDsMUuDKliqGFdU}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh geometry={nodes.Object_42.geometry} material={materials.CRQixVLpahJzhJc}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh geometry={nodes.Object_48.geometry} material={materials.YYwBgwvcyZVOOAA}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh geometry={nodes.Object_54.geometry} material={materials.SLGkCohDDelqXBu}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh geometry={nodes.Object_58.geometry} material={materials.WnHKXHhScfUbJQi}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh geometry={nodes.Object_66.geometry} material={materials.fNHiBfcxHUJCahl}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh geometry={nodes.Object_74.geometry} material={materials.LpqXZqhaGCeSzdu}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh geometry={nodes.Object_82.geometry} material={materials.gMtYExgrEUqPfln}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh geometry={nodes.Object_96.geometry} material={materials.PaletteMaterial003}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh geometry={nodes.Object_107.geometry} material={materials.JvMFZolVCdpPqjj}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh geometry={nodes.Object_127.geometry} material={materials.ZCDwChwkbBfITSW}
                  rotation={[Math.PI / 2, 0, 0]}/>
        </group>
    )
}

export default MacbookModel16;

useGLTF.preload('/models/macbook-16-transformed.glb')
